darwinia:
  - config: daos/ring-dao.yml
    state: active
  - config: daos/kton-dao.yml
    state: active
  - config: daos/ring-dao-guild.yml
    state: active

  - config: daos/degov-no-timelock.yml
    state: active
    tags:
      - demo
  - config: daos/degov-blocknumber.yml
    state: active
    tags:
      - demo
  - config: https://demo.degov.ai/degov.yml
    state: active
    domains:
      - demo.degov.ai
    tags:
      - demo

ethereum:
  - config: daos/ens-dao.yml
    state: active
  # - config: daos/truefi-dao.yml
  - config: daos/fluence-dao.yml
    state: active
  - config: daos/instadapp-dao.yml
    state: active
  - config: daos/radworks-dao.yml
    state: active
  - config: daos/compound-dao.yml
    state: active
  - config: daos/gitcoin-dao.yml
    state: active
  - config: daos/threshold-dao.yml
    state: active
  - config: daos/obol-dao.yml
    state: active
  - config: daos/adventure-gold-dao.yml
    state: active
  - config: daos/ampleforth-dao.yml
    state: active
  - config: daos/antfarm-dao.yml
    state: active
  - config: daos/anvil-dao.yml
    state: active
  - config: daos/bytom-dao.yml
    state: active
  - config: daos/cryptex-dao.yml
    state: active
  - config: daos/dive-staking-dao.yml
    state: active
  - config: daos/dope-dao.yml
    state: active
  - config: daos/flayer-dao.yml
    state: active
  - config: daos/hifi-dao.yml
    state: active
  - config: daos/idle-dao.yml
    state: active
  - config: daos/kroma-security-council-dao.yml
    state: active
  - config: daos/lightchain-dao.yml
    state: active
  - config: daos/ondo-dao.yml
    state: active
  - config: daos/openscan-dao.yml
    state: active
  - config: daos/public-nouns-dao.yml
    state: active
  - config: daos/reflexer-dao.yml
    state: active
  - config: daos/silo-dao.yml
    state: active
  - config: daos/sudoswap-dao.yml
    state: active
  - config: daos/union-dao.yml
    state: active


base:
  - config: daos/aquari-dao.yml
    state: active
    domains:
      - gov.aquari.org
  - config: daos/unlock-dao.yml
    state: active
  - config: daos/carv-dao.yml
    state: active
  - config: daos/awe-dao.yml
    state: active
  - config: daos/internet-token-dao.yml
    state: active
  - config: daos/lazy-summer.yml
    state: active
  - config: daos/seamless-dao.yml
    state: active
  - config: daos/aixbt-dao.yml
    state: active
  - config: daos/fame-dao.yml
    state: active
  - config: daos/virtuals-dao.yml
    state: active

arbitrum:
  - config: daos/rn-dao.yml
    state: active
  - config: daos/gmx-dao.yml
    state: active
  - config: daos/content-guild-dao.yml
    state: active
  - config: daos/opendollar-daoy.yml
    state: active

optimism:
  - config: daos/hai-dao.yml
    state: active

lisk:
  - config: daos/lisk-dao.yml
    state: active

blast:
  - config: daos/ring-protocol-dao.yml
    state: active

bnb-smart-chain:
  - config: daos/ark-dao.yml
    state: active
  - config: daos/bsc-dao.yml
    state: active
